# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/nesibegul/Visualization/blob/main/Welcome_To_Colaboratory.ipynb

## Global death rates visualization
## 1. Install and import libraries
"""

!pip install geopandas

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly
import geopandas
import plotly.express as px
import plotly.graph_objects as go

"""### 1.1 Set options"""

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

"""## 2. Reading data

Global Causes of Death is an important study on causes of death and illness, published in the medical journal The Lancet. In the global causes of death data, the rates of deaths in each country between 1990 and 2016 were kept for reasons such as illness, illness, terrorism, and traffic accidents. In the data, besides the countries, there are also death cause rates for places such as the world, some communities, Central Asia and Eastern Europe. Since the causes of death data are given only as a ratio, operations such as summing and averaging cannot be performed, which causes limitations in extracting information while analyzing the data.
"""

data = pd.read_excel('https://github.com/rfordatascience/tidytuesday/blob/master/data/2018/2018-04-16/global_mortality.xlsx?raw=true', na_values=0)

data.head()

"""In the data, after the country name, country code and year columns, each of the causes of death is kept as a column. Since this situation will make it difficult to analyze the data, all causes of death in the future have been put under a single column.

## 2.1 Dropping the rows whose country codes are not exist
Since the country_code column is used when visualizing the data and then combining it with the continent names, the null rows here are excluded from the dataset.
"""

data.isnull().sum()

data[data['country_code'].isnull()]['country'].unique()

data1  = data.dropna(subset = ['country_code'])

"""## 2.2 Deleting the " (%)" sign from the column names"""

data1.describe()

"""There are 5292 rows in the data. Diseases are kept as percentages in separate horizontal columns. The highest rate of death due to any reason in any country belongs to conflicts (Conflict (%)) with 82,317%.
The data types are appropriate and we don't need to convert them.
"""

data1.info()

"""The "(%)" signs in the column names have been removed."""

data1.columns=data1.columns.str.replace('[(%)]','').str.strip()
data1.columns

"""## 3. Unpivoting the columns related to death causes
In order to analyze the data more easily with pandas functions, the causes of death in the data were reshaped in one column and the death rates in one column.
"""

mortality_reasons = data1.columns[3:]
data1 = data1.groupby(['country', 'country_code', 'year'])[mortality_reasons].mean().reset_index()
data_melted = data1.melt(id_vars=['country', 'country_code', 'year'], var_name='mortality_reasons', value_name='percent')
data_melted.head()

"""## 4. Visualization of the max death causes by country and year


In the first visualization, it was desired to find the cause with the highest mortality rate in each country by year. The aim is to see the change in the most common causes of death depending on the years, and to find answers to questions such as is there a grouping in the world in the causes of death with the highest percentage.
"""

data_year_and_country_based_max = data_melted.loc[data_melted.groupby(['country', 'country_code', 'year'])['percent'].idxmax()]

## Choropleth map
import plotly.express as px
fig = px.choropleth(data_year_and_country_based_max, locations="country_code", color="mortality_reasons", 
                    hover_name="country", hover_data = ['percent'], animation_frame="year", range_color=[0, 0.5], labels={"mortality_reasons": "mortality reasons"})
fig.update_layout({'title': {'text': "Ülke bazında en yüksek orana sahip ölüm sebeplerinin yıllara göre değişimi", 'x': 0.45, 'y': 0.95}})
fig.show()



"""Table 1: Causes of death with the highest rate by country and year

According to Table 1:
*  The predominant cause of death worldwide is cardiovascular disease.
*  In South Africa, especially in the early years, in many countries, besides cardiovascular disease, diarrhea, tuberculosis and HIV/AIDS-related diseases caused the most deaths.
*  Again, malaria in Africa and Bangladesh, lower respiratory infections diseases in African and Latin American countries are striking.
*  Since the beginning of the 2000s, cancer has been observed as the most common cause of death in Greenland and France, followed by the Americas.

## 5. Visualization of the top 5 diseases that cause the most deaths by continent and year
Continent names were needed to show the first 5 diseases on a continent basis by bar graphs.
Since we do not have continent names in our data, let's take it from another data source and combine it and draw bar graphs of the top 5 disturbances by continent and year.
"""

#Verinin okunması ve kullanılacak kolonların seçilmesi
country_contitent = pd.read_csv('https://gist.githubusercontent.com/stevewithington/20a69c0b6d2ff846ea5d35e5fc47f26c/raw/13716ceb2f22b5643ce5e7039643c86a0e0c6da6/country-and-continent-codes-list-csv.csv')
country_contitent = country_contitent[['Continent_Name', 'Country_Name', 'Three_Letter_Country_Code' ]]
country_contitent.head()

#Verilerin ülke kodları üzerinden birleştirilmesi
data_with_contitent = pd.merge(data_melted, country_contitent, how = 'inner', left_on= 'country_code', right_on= 'Three_Letter_Country_Code')
data_with_contitent.head()

# Kıta ve yıllar bazında  ilk 5 rahatsızlığın elde edilmesi
top_reasons = data_with_contitent.groupby(['Continent_Name', 'year' ,'mortality_reasons'])['percent'].mean().reset_index()

results = []
for name, group in top_reasons.groupby(['Continent_Name', 'year']):
    top_5 = group.sort_values(by='percent', ascending=False).head(5)
    results.append(top_5)

# Concatenate the results into a single DataFrame
top_reasons_df = pd.concat(results)
top_reasons_df = pd.DataFrame(top_reasons_df)
top_reasons_df.head(10)

#Verinin görselleştirilmesi
fig_bar = px.bar(top_reasons_df, x="mortality_reasons", y="percent",  
                 animation_frame="year",  facet_col = 'Continent_Name', color ='mortality_reasons', hover_data = [ 'percent'],
                 width = 1500, height = 800, labels = {
        'mortality_reasons': '',
        'percent': 'Yüzde',
        'Continent_Name': 'Kıta',
        'year':'Sene'
    } ,  color_discrete_sequence=px.colors.qualitative.T10)

#fig_bar.update_yaxes(showgrid=False)
fig_bar.update_layout({'title': {'text': "Kıtalar bazında ölüme sebep olan ilk 5 hastalığın yıllara göre değişimi ", 'x': 0.45, 'y': 0.85}})
fig_bar.update_xaxes(categoryorder='total descending')

#fig_bar.update_layout({'xaxis':{'title':{'text':''}}, 'yaxis':{'title':{'text':'%'}}})
fig_bar.update_traces(hovertemplate=None)

fig_bar.update_layout(
                        hovermode="x unified",
                        
                        xaxis_title=' ', yaxis_title=" ",
                        
                        title_font=dict(size=25, color='#a5a7ab', family="Lato, sans-serif"),
                        font=dict(color='#8a8d93'),
                        legend=dict(orientation="v", yanchor="bottom", y=1.07, xanchor="right", x=1)
                          )

fig_bar['layout']['updatemenus'][0]['pad']=dict(r= 10, t= 180)
fig_bar['layout']['sliders'][0]['pad']=dict(r= 10, t= 180,)


names={'Africa':'Plot1','Asia':'Plot2', 'Europe':'Plot3','North America':'Plot4', 'Oceania':'Plot5','South America':'Plot6' }
for i, label in enumerate(names):
    fig_bar.layout.annotations[i]['text'] = label


fig_bar.show()

"""Table 2: Top 5 diseases that cause the most deaths by continent and years

*  Cardiovascular diseases cause the most deaths every year on all continents.
*  Deaths due to cardiovascular diseases are mostly in the European continent.

*  Diseases that are specific to the African continent but cannot be included in the top 5 in other continents in any year are HIV/AIDS, diarrhea and malaria.
*  Dementia, respiratory diseases, natural disasters, and diabetes have not been in the top 5 at any time in the African continent.
*  After cardiovascular diseases for many years in Africa, HIV/AIDS caused the most death toll.
*  Until 2005, deaths from respiratory diseases in any continent other than Europe and Oceania did not enter the top 5 . After 2005, it has been in the top 5 in Asia and South America.
*  Conflict-related death rates were only in the top 5 in the Asian continent in 2014 and 2016.

## 6. Comparison of mortality rates due to cardiovascular diseases in Turkey with the World, Central Europe and Central Asia by years
Cardiovascular diseases with line and scatter graphs
*  Turkey-World
*  Turkey-Central Europe
*  Turkey-Central Asia
The rates of deaths between years were compared.
"""

data_turkey_world = data[data['country'].isin(['World', 'Turkey', 'Central Europe', 'Central Asia' ]) ]
data_turkey_world.columns=data_turkey_world.columns.str.replace('[(%)]','').str.strip()
data_turkey_world_melted = data_turkey_world.melt(id_vars=['country', 'country_code', 'year'], var_name='mortality_reasons', value_name='percent')
data_turkey_world_melted.sort_values(by = 'country')
data_turkey_world_melted_cardio = data_turkey_world_melted[data_turkey_world_melted['mortality_reasons']== 'Cardiovascular diseases']
data_turkey_world_melted_cardio.drop(['country_code'], axis = 1, inplace = True)


fig = go.Figure()
for place in ['Turkey', 'World', 'Central Europe', 'Central Asia']:
    df = data_turkey_world_melted_cardio[data_turkey_world_melted_cardio.country == place]
    fig.add_trace(go.Scatter(
                x = df['year'],
                y = df['percent'], 
                mode = 'lines', name = place))#not line plot
fig.update_layout({'title': {'text': "Kardiyovasküler rahatsızlığa bağlı ölüm oranlarının yıllara göre değişimi", 'x': 0.5, 'y': 0.9}})
fig.update_layout({'xaxis':{'title':{'text':''}}, 'yaxis':{'title':{'text':'%'}}})

my_sliders = [
    {'steps':[
        
    {'method':'update', 'label':'All Places', 
    'args':[{'visible': [True, True, True, True]}]},
        
    {'method':'update', 'label':'Turkey vs World', 
    'args':[{'visible': [True, True, False, False]}]},
        
    {'method':'update', 'label':'Turkey vs Central Europe', 
    'args':[{'visible': [True, False, True, False]}]},
         
    {'method':'update', 'label':'Turkey vs Central Asia', 
    'args':[{'visible': [True, False, False, True]}]},
    
    ]}  ]
fig.update_layout({'sliders':my_sliders})

my_button = [
   { "label":"Line plot","method": "update", "args":[{"type":"scatter", "mode":"lines"}]},
   {"label": "Scatter plot", "method":"update", "args":[{"type":"scatter", "mode":"markers"}]}
      ]

fig.update_layout({"updatemenus":[{"type":"buttons",
                                   "direction":"down",
                                   "x":1.1, "y":0.7,
                                   "showactive":True,
                                   "active":0,
                                   "buttons":my_button}]})



fig.show()

"""Table 3: Comparison of mortality rates due to cardiovascular diseases in Turkey, the World, Central Europe and Central Asia by years

*  Mortality rates due to cardiovascular diseases increase over time in Turkey.
*  Mortality rates due to cardiovascular diseases in Turkey are above the world average, but are quite low compared to underdeveloped Central Asia and highly developed Central Europe.
*  Central Europe was only able to reduce the death rate from cardiovascular diseases to 51% over time, from the rate of 55%.
*  Contrary to Central Europe, death rates due to cardiovascular diseases have increased over time in the World and Central Asia, like Turkey.
"""

